### ISSUE TITLE
买了您的书。但是第七章的人头计数没有提供  people_counter.py  文件

### ISSUE THREAD

**Issue by liuyanghan** [r0ysue/RaspPyOpenCV#1]

**Comment by 2240173817** [comment]
https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/，看这个链接吧 作者也是炒的别人 来讲解得

**Comment by 2240173817** [comment]
https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/    ，    看这个连接吧，作者一摸一样拿过来的，做了翻译罢了

**Comment by r0ysue** [comment]
按照这个帖子来对的，实践了是ok的。
